name: Docker Image CI


on:
  push:
    branches: [ "na" ]
  pull_request:
    branches: [ "na" ]

jobs:
  integration:
    uses: ./.github/workflows/python-ci-workflow.yml
    permissions:
      contents: read
      checks: write
    
  build:
    needs: [integration]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
